### ISSUE TITLE
Any ETA when the trained model will be published? 

### ISSUE THREAD

**Issue by reneschulte** [facebookresearch/DeepFovea#1]
Intentionally left blank. 😉

**Comment by mmehas** [comment]
Hi Rene, thanks for your question. We are going through some internal approval processes to publish the model and we don't have a specific ETA that we can share, sorry. It shouldn't take too long, though.

**Comment by reneschulte** [comment]
Why is this closed? Can't we wait until it is actually released?

**Comment by mmehas** [comment]
I was assuming that since we provided the answer, the issue could be closed. If that would help, let's reopen it. We will post an update here when we publish the model.

**Comment by reneschulte** [comment]
Thank you @mmehas Really appreciate it. 
For me it's a great way to make sure I don't miss it and get a notification in my mailbox.

**Comment by CianNoonan** [comment]
I appreciate that Christmas has probably derailed this but any update on the approval for release here? I'm really interested in seeing the full dataset at work

**Comment by mmehas** [comment]
Hi @CianNoonan, we appreciate your interest, and sorry for the delay. The process is almost finished though and we should be able to publish the working model in the upcoming weeks.

**Comment by DenisSergeevitch** [comment]
Hi, any news about the trained model? :)

**Comment by mmehas** [comment]
@DenisSergeevitch, at the moment we are done with the technical details and preparing a short blogpost\documentation to accompany the release.

**Comment by DenisSergeevitch** [comment]
@mmehas looking forward to try it, you are amazing :)

**Comment by jonnyawsom3** [comment]
Just found this via youtube (presumably like many others) and I'm quite interested by it's video compression capabilities.

Glad to hear there's activity and hopefully one day someone will be able to whip up a small GUI application for it.
(So compressing a video would be "select input video, compression percentage, output name" and then "select video, output name" for... Extraction? I'm not quite sure what to call it... Interpolation may be the right word)

Hope to hear more soon!

**Comment by kaplanyan** [comment]
Today, we are excited to release the full DeepFovea demo, so the researchers can experience the neural foveated rendering and reproduce the results of our DeepFovea paper either on a screen or in a headset. Thanks to the novel generative AI algorithm, DeepFovea sets a new milestone in foveated rendering with only 10% of pixels needed to reconstruct the full image. Please check out the new instructions on how to run the demo. If you are interested to learn more about how DeepFovea was designed, you can check out this new post as well https://research.fb.com/blog/2020/05/deepfovea-ar-vr-rendering-inspired-by-human-vision/

Best,
The DeepFovea team

**Comment by reneschulte** [comment]
Awesome. Thanks @kaplanyan 👏
