### ISSUE TITLE
load input_graph.pb

### ISSUE THREAD

**Issue by dgiunchi** [facebookresearch/DeepFovea#2]
I try to load in TensorFlow the input_graph.pb but I got this error:
"google.protobuf.message.DecodeError: Wrong wire type in tag."

I used this simple code (tried with tf 1.5.1 and 2.4.1, on windows 10)
```
import tensorflow as tf
from tensorflow.python.platform import gfile
GRAPH_PB_PATH = './input_graph.pb'
with tf.Session() as sess:
   print("load graph")
   with gfile.FastGFile(GRAPH_PB_PATH,'r') as f:
       graph_def = tf.GraphDef()
   graph_def.ParseFromString(f.read())
   sess.graph.as_default()
   tf.import_graph_def(graph_def, name='')
   graph_nodes=[n for n in graph_def.node]
   names = []
   for t in graph_nodes:
      names.append(t.name)
   print(names)

```
I tried to open it also in Netron but I got an error as well.
Do I do something wrong?

Update
----->
After converting from pbtxt to pb it worked

**Comment by ArenaGrenade** [comment]
Hey @dgiunchi! Were u able to figure how to use the pre-trained model? If yes could you please share any pointers as to how I can find out what the input and output nodes are? (There is not much info out here)
